## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding 

### Nominal/OHE Encoding
One hot encoding, also known as nominal encoding, is a technique used to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [9]:
%pip install --upgrade numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [1]:


import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
## Create a simple dataframe 
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'green', 'red', 'blue']
})

In [4]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [2]:
##create an instance of Onehotencoder
encoder=OneHotEncoder()

In [12]:
## perform fit and transfor
encoded=encoder.fit_transform(df[['color']]).toarray()

In [13]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [14]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [15]:
encoder_df

color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [15]:
## for new data
encoder.transform([['blue']]).toarray()

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [16]:
pd.concat([df,encoder_df],axis=1)

color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [19]:
import seaborn as sns
data_set = sns.load_dataset('tips')

In [20]:
data_set.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
encoded_data_set = encoder.fit_transform(data_set[['sex', 'smoker', 'day', 'time']]).toarray()

In [30]:
encoded_data_set

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [28]:
encoder.transform([['Female','Yes','Sun','Dinner']]).toarray()

c:\Users\am536\OneDrive\Documents\Machine-Learning\venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0., 1., 0., 0., 1., 0., 1., 0.]])

In [23]:
encoded_df = pd.DataFrame(encoded_data_set, columns=encoder.get_feature_names_out())

In [24]:
new_data_set = pd.concat([data_set, encoded_df], axis=1)
new_data_set.head()

total_bill   tip     sex smoker  day    time  size  sex_Female  sex_Male  \
0       16.99  1.01  Female     No  Sun  Dinner     2         1.0       0.0   
1       10.34  1.66    Male     No  Sun  Dinner     3         0.0       1.0   
2       21.01  3.50    Male     No  Sun  Dinner     3         0.0       1.0   
3       23.68  3.31    Male     No  Sun  Dinner     2         0.0       1.0   
4       24.59  3.61  Female     No  Sun  Dinner     4         1.0       0.0   

   smoker_No  smoker_Yes  day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  \
0        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
1        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
2        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
3        1.0         0.0      0.0      0.0      1.0       0.0          1.0   
4        1.0         0.0      0.0      0.0      1.0       0.0          1.0   

   time_Lunch  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0

### Label Encoding 
Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable "color" with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [19]:
df.head()

color
0    red
1   blue
2  green
3  green
4    red

In [20]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [21]:
lbl_encoder.fit_transform(df[['color']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [23]:
lbl_encoder.transform([['red']])

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:134: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [24]:
lbl_encoder.transform([['blue']])

array([0])

In [25]:
lbl_encoder.transform([['green']])

array([1])

### Ordinal Encoding
It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1
2. College: 2
3. Graduate: 3
4. Post-graduate: 4

In [26]:
## ORdinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [27]:
# create a sample dataframe with an ordinal variable
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [28]:
df

size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [30]:
## create an instance of ORdinalEncoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [31]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [32]:
encoder.transform([['small']])

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])