In [1]:
import numpy as np

In [2]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [3]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1)

[[1 2 3]
 [4 5 6]]


In [4]:
import pandas as pd 

In [ ]:
df1 = pd.DataFrame({})